API_KEY = "aa14874600855457b5a838ec894a06ae"
WEATHER_API_KEY = "mOpwoft03br5cj7z"
NEXTJS_CHECK_SUB_URL = "https://my-football-zeta.vercel.app/api/check-subscription"
JWT_SECRET = "Q/X62wPT1Co1l7XWpWjRqZxF0bsg8vbBFrdAUk3u/DU="
