API_KEY = "aa14874600855457b5a838ec894a06ae"
WEATHER_API_KEY = "mOpwoft03br5cj7z"
NEXTJS_CHECK_SUB_URL = "https://www.foot-predictions.com/api/check-subscription"
JWT_SECRET = "Q/X62wPT1Co1l7XWpWjRqZxF0bsg8vbBFrdAUk3u/DU="
OPENAI_API_KEY = "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"
