API_KEY = "aa14874600855457b5a838ec894a06ae"
WEATHER_API_KEY = "mOpwoft03br5cj7z"
NEXTJS_CHECK_SUB_URL = "https://my-football-zeta.vercel.app/api/check-subscription"
JWT_SECRET = "Q/X62wPT1Co1l7XWpWjRqZxF0bsg8vbBFrdAUk3u/DU="
openai.api_key = "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"
